name: todo_app_pro
description: A professional task management app with Clean Architecture
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # State Management
  flutter_riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5

  # Firebase
  firebase_core: ^2.24.2
  firebase_auth: ^4.16.0
  cloud_firestore: ^4.14.0
  google_sign_in: ^6.2.1
  google_sign_in_android: ^6.1.25

  # Local Storage
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  # Code Generation
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1

  # UI Components
  google_fonts: ^6.1.0
  flutter_slidable: ^3.0.1
  flutter_animate: ^4.5.0
  shimmer: ^3.0.0
  flutter_svg: ^2.2.2

  # Utilities
  intl: ^0.19.0
  uuid: ^4.3.3
  connectivity_plus: ^5.0.2
  equatable: ^2.0.5
  dartz: ^0.10.1

  # Routing
  go_router: ^13.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.8
  freezed: ^2.4.6
  json_serializable: ^6.7.1
  hive_generator: ^2.0.1
  riverpod_generator: ^2.3.11

flutter:
  uses-material-design: true
  assets:
    - assets/images/todo2.png
    - assets/images/google signin.svg
    - assets/icons/